#!/bin/bash

# this script installs Brave repo and GPG key interactively,
# sets their permissions to chown root:root and write-protected,
# and installs stable, beta or nightly using rpm-ostree

# I silenced all error messages as they where plenty of them. But the commands are all chained together, so if one fails, all fail

REPO-BASEURL="https://brave-browser-rpm-release.s3.brave.com" 2> /dev/null
KEY-BASEURL=$REPO-BASEURL 2> /dev/null

# User input for Brave version
read -r -p "Which version of Brave do you want to install? (stable/beta/nightly): " brave_version

# Determine repository URL and GPG key based on user's choice
case "$brave_version" in
    stable)
        curl -LsS $REPO-BASEURL/brave-browser.repo 2> /dev/null | sudo tee /etc/yum.repos.d/brave-browser.repo > /dev/null &&\
        curl -LsS $KEY-BASEURL/brave-core.asc 2> /dev/null | sudo tee /etc/pki/rpm-gpg/brave-core.asc > /dev/null &&\
        echo "" &&\
        echo "Repo and Key downloaded." &&\
        echo "installing..." &&\
        rpm-ostree install brave-browser
        ;;

    beta)
        curl -LsS $REPO-BASEURL/brave-browser-beta.repo 2> /dev/null | sudo tee /etc/yum.repos.d/brave-browser-beta.repo > /dev/null &&\
        curl -LsS $KEY-BASEURL/brave-core-nightly.asc 2> /dev/null | sudo tee /etc/pki/rpm-gpg/brave-core-nightly.asc > /dev/null &&\
        echo "" &&\
        echo "Repo and Key downloaded." &&\
        echo "installing..." &&\
        rpm-ostree install brave-browser-beta
        ;;

    nightly)
        curl -LsS $REPO-BASEURL/brave-browser-nightly.repo 2> /dev/null | sudo tee /etc/yum.repos.d/brave-browser-nightly.repo > /dev/null &&\
        curl -LsS $KEY-BASEURL/brave-core-nightly.asc 2> /dev/null | sudo tee /etc/pki/rpm-gpg/brave-core-nightly.asc > /dev/null &&\
        echo "" &&\
        echo "Repo and Key downloaded." &&\
        echo "installing..." &&\
        rpm-ostree install brave-browser-nightly
        ;;

    *)
        echo "Invalid choice. Use 'Ctrl+c' to exit." &&\
        read -r -p "Which version of Brave do you want to install? (stable/beta/nightly): " brave_version
        ;;
esac
